Update README.md delete changlog and release planning
INSPIRE-MIF/helpdesk-validator pull request #240
Opened 2020-03-04 15:57 UTC by juanpelegrina

2020-03-04 18:31 UTC, MarcoMinghini requested changes
I would rephrase the last sentence as suggested.

2020-03-04 18:31 UTC, MarcoMinghini commented on README.md
> +Please check [Releases](https://github.com/inspire-eu-validation/community/releases) for current features and the [Release Strategy](https://github.com/inspire-eu-validation/community/tree/master/rel
Please check the [changelog of the current and past releases](https://github.com/inspire-eu-validation/community/releases) and the [release planning strategy](https://github.com/inspire-eu-validation/community/tree/master/release%20strategy) for the plan of future releases of the INSPIRE Reference Validator.

2020-03-04 19:48 UTC, jenriquesoriano approved these changes
It's ok for me, I agree with Marco's proposal

2020-03-04 19:52 UTC, juanpelegrina commented
Thanks, I will implement the suggested  changes first thing in the morning

2020-03-05 07:41 UTC, MarcoMinghini approved these changes

2020-03-05 07:41 UTC, merged